### PR TITLE
ci: use setup-cpp to set up all compilers and tools for all the CI services (GitHub, Gitlab, etc.)

### PR DESCRIPTION
**Pull request by aminya**
https://github.com/aminya/setup-cpp

use setup-cpp to set up all compilers and tools for all the CI services (GitHub, Gitlab, etc.). This includes different compilers and platforms:

image

### CODE REVIEW

**Review by lefticus — APPROVED** [review]
I'm in favor of more automated setup, and more CI tests

**Comment by lefticus** [comment]
should we drop appveyor? Does it make sense to keep maintaining it when github actions are so easy to use?

**Comment by aminya** [comment]
> should we drop appveyor? Does it make sense to keep maintaining it when github actions are so easy to use?

I agree. I removed it. You should also disable its app from the settings.

**Review by ddalcino — COMMENTED** [review]
I guess my approval doesn’t matter now, but this looks really good to me. Nice work, @aminya!

**Pull request merged**
